version: '3.8'

services:
  backend:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allowing Docker to access the host's Docker daemon
    ports:
      - "8000:8000"
    privileged: true  # To run Docker-in-Docker
    environment:
      - NODE_ENV=development
